export const GLOBAL = {
  SET_LOADING: 'SET_LOADING',
  SET_MESSAGE: 'SET_MESSAGE',
  RESET_MESSAGE: 'RESET_MESSAGE'
}

export const CLIENT = {
  CLIENT_SET: 'CLIENT_SET',
  SET_CLIENT_CONFIG: 'SET_CLIENT_CONFIG',
  RESTORE_CLIENT_CONFIG: 'RESTORE_CLIENT_CONFIG',
  SET_CLIENT_ID: 'SET_CLIENT_ID'
}

export const RECEPTION = {
  RECEPTIONS_SET: 'RECEPTIONS_SET'
}

export const INVITE = {
  INVITES_SET: 'INVITES_SET',
  RECEPTIONS_SET: 'RECEPTIONS_SET'
}

export const GUEST = {
  GUEST_REGISTER_SET: 'GUEST_REGISTER_SET',
  GUEST_DOCUMENT_NUMBER_SET: 'GUEST_DOCUMENT_NUMBER_SET',
  GUEST_DOCUMENT_TYPE_SET: 'GUEST_DOCUMENT_TYPE_SET'
}

export const AUTH = {
  SET_USER: 'SET_USER'
}
